= Peacetrue Async Validator

基于 https://github.com/yiminghe/async-validator[Async Validator^] 的扩展，提供更多的特性支持。

== 验证规则
验证规则包括如下方法：

* 注册验证规则
* 使用验证规则
* 设置语言
//* 设置错误描述
* 设置本地化字段

=== 自定义验证规则

[source%nowrap,javascript]
----
let Rules = require('./src/rules');
//注册验证规则
Rules.register(require('./src/required_if'));
//验证规则格式：
{
    name:String,//规则名
    rule:function(rule, value, callback, source, options){//规则函数
        //参数与 async-validator 的 validator 相同
        //在rule上添加一些额外字段：
        //rule.规则名 = 规则选项
    },
    //错误描述，支持使用占位符，格式为：{字段名}
    //支持字段名嵌套，例如：{字段名.字段名}
    //支持国际化，传入字符串不区分语言，传入对象区分语言
    message:String|Object,
}
//错误描述占位符支持的选项，例如：{source}有值时，{target}必须有值
{
    _field:String,//当前验证的字段，加前缀_，避免和规则选项的属性重名
    _value:*,//当前验证字段的值
    ...:*,//规则选项的属性
}
//错误描述国际化支持
{
 '*':String,//默认值，没有配置指定语言的错误描述时，使用该描述
 'zh_CN':String,//简体中文
 ...:String,//其他语言
}

//使用验证规则
let Validator = require('async-validator');
let rule = Rules.use('requiredIf', {source:'name',target:'sex'});//用户名有值时，性别必须有值
Rules.use=function(name,options){
    //name:规则名，
    //options:规则选项，不同的规则具有不同的选项
}

let descriptor = {user: [{type: 'object'}, rule],};
let validator = new Validator(descriptor);
----

=== 错误描述国际化
[source%nowrap,javascript]
----
let Rules = require('./src/rules');
//不设置语言，默认为中文
Rules.setLang=function(lang){
    //lang：语言
}
----

=== 设置本地化字段
默认情况下，会直接提示英文字段名，比如说：name 必须是唯一的，
你可以通过``Rules.setField``为其设置字段描述：

[source%nowrap,javascript]
----
let Rules = require('./src/rules');
//不设置直接展示字段名，设置后展示字段描述
Rules.setField=function(name,desc){
    //name：字段名
    //desc：字段描述
}
Rules.setFields=function(names){
    Object.keys(names).forEach(key=>{
        //key=字段名
        //names[key]=字段描述
    });
}
----


=== requires
多个属性中至少有一个有值，有值指不为``null`` 或者 ``undefined`` 或者 ``""``。

关于起名：required 已经被占用了，requireds 不是一个有效单词，所以使用了 requires。

应用于对象上，示例如下：
[source%nowrap,javascript]
----
{requires:{
    fields:Array,//指定哪些属性必须至少有一个
    message:String,//错误描述，默认值为："{fields}中至少有一个不为空"
}}
----

=== requiredIf
如果属性source有值，则属性target必须有值；
属性source无值，则属性target可以有值也可以无值。

//sync:Boolean,//是否同步，为true则属性target无值时，属性source也必须无值，默认为false。

应用于对象上，示例如下：
[source%nowrap,javascript]
----
{requiredIf:{
    source:String,//属性source
    target:String,//属性target
    message:String,//错误描述，默认值为："{source}有值时，{target}必须有值"
}}
----


=== unique
属性在数据库中必须是唯一的。

应用于属性上，示例如下：
[source%nowrap,javascript]
----
{unique:{
    url:String,//链接地址
    params:function(options){//请求参数，可选
        //options.field:当前验证的属性
        //options.value:当前验证属性的值
        return {[options.field]:options.value};//默认实现
    },
    successHandler:function(response){return Boolean};//成功时的处理函数，格式化响应结果，返回一个boolean值，可选，默认为null，直接返回response
    errorHandler:function(response){};//请求出错时的处理，可选，默认为null
    original:*,//原始值，如果属性值未发生变化时，直接校验为通过，不用请求后台
    message:String,//错误描述，默认值为："{_field}必须是唯一的"
}}
----
请求出错后，无法得到有效验证结果，忽略此次验证。

== 中文错误描述
因为内置的错误描述不支持中文，
原本是可以通过``AsyncValidator.messages``设置本地错误描述的，
与 iview 集成后，iview 没有提供相应的接口：

.iview/src/components/form/form-item.vue[193,206]
[source%nowrap,javascript]
----
let descriptor = {};
descriptor[this.prop] = rules;

const validator = new AsyncValidator(descriptor);
let model = {};

model[this.prop] = this.fieldValue;

validator.validate(model, { firstFields: true }, errors => {
    this.validateState = !errors ? 'success' : 'error';
    this.validateMessage = errors ? errors[0].message : '';

    callback(this.validateMessage);
});
----

只能在验证时，提供错误描述；
总是手写错误描述过于繁琐，所以提供了一个错误描述生成器：

[source%nowrap,javascript]
----
let Message = require('../src/message_generator');

let descriptor = {name:[
    {type: 'string'},
    {required: true},
    {min: 3, message: '至少 3个字符'},
    {max: 8}
]};
//每个规则必须单独是一项，type必须是第一项，如果第一项不是type，则type默认为string，后续不要再使用type了

Message.generate(descriptor);
//descriptor会自动添加message信息：
{
  name: [
    { type: 'string', message: 'name 不是一个 字符串' },
    { required: true, message: 'name 是必须的' },
    { min: 3, message: '至少 3个字符' },
    { max: 8, message: 'name 不能够长于 8 个字符' }
  ]
}
//已经有message的，不会重复生成

----


== 字段名本地化
默认情况下，会提示 name 不是一个 字符串，
如果要将 name 也本地化，在生成时需要提供字段名的本地化描述。

[source%nowrap,javascript]
----
let Message = require('../src/message_generator');

let descriptor = {name:[
    {type: 'string'},
    {required: true},
    {min: 3, message: '至少 3个字符'},
    {max: 8}
]};

Message.generate(descriptor,{name: '姓名'});
//descriptor会自动添加message信息：
{
  name: [
    { type: 'string', message: '姓名 不是一个 字符串' },
    { required: true, message: '姓名 是必须的' },
    { min: 3, message: '至少 3个字符' },
    { max: 8, message: '姓名 不能够长于 8 个字符' }
  ]
}
----







